require:
  - rubocop-performance
  - rubocop-rspec

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

RSpec/NestedGroups:
  Max: 5

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'
